### ISSUE TITLE
Underscore instead of dash in Id value

### ISSUE THREAD

**Issue by gangparia** [Draggable/formeo#110]
Is this possible, formeo have underscore instead of ids.

**Comment by kevinchappell** [comment]
What is the use case? It is possible to change but I'd like to know why before considering such a change since hyphen-case is generally accepted best practice for ids.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

https://gist.github.com/ryansechrest/8693303#5-elements-and-attributes

**Comment by gangparia** [comment]
Thanks for sharing info.
